### ISSUE TITLE
Feature Request: more scaling options

### ISSUE THREAD

**Issue by kaedys** [marconsou/mp-tick-bar#1]
Currently, the scaling control has a minimum of 1.0, despite the bar being relatively large.  In addition, it'd be useful if the bar had either a height or width scale setting in addition, to permit changes to the bar's relative aspect ratio.  Personally, I'd like the make the bar a bit smaller on width, but also slightly taller, so it fits into a specific spacing on my HUD.

**Comment by marconsou** [comment]
For all number-inputs, you can insert whatever value you wish by just pressing ctrl + click on it. The minimum/maximum works more like a suggestion/safe value for user.

For width/height options: i didn't add those options just because to keep aspect ratio (and don't distorce elements like number percentage), so we have 2 situations:
-Keep the UI scale for Width and Height separately, so every single UI element scales together.
-Add an absolute/pixel for width and height just for bar (while keeping the current ui scale), but the other UI elements may change: the marker inside bar will need to scale with this option and it will change the starting position of some elements too (some of them are relative to bar width).

I would prefer the first option if that's the case, because adding another scale over an already existing scale it might be a bit confusing on user perspective.

I think what you want it's more like the second option?

**Comment by marconsou** [comment]
I gonna do some tests and see how it will work:

-General: one scale to keep aspect ratio that affect everything (i gonna need to add a new tab for general use, in this case)
-Progress Bar: scale width and height separately will affect the bar itself and the Fire III Marker inside bar.
-Fire III Marker: no scale options because option above. (maybe i change this, not sure)
-Remaining elements: for each element, one scale to keep aspect ratio.

I gonna change the minimum value for scale to 0.1

**Comment by kaedys** [comment]
Awesome, much appreciated!
