### ISSUE TITLE
only dark knight shows up as alternative job

### ISSUE THREAD

**Issue by jacob-keller** [marconsou/mp-tick-bar#6]
The tick based countdown would be very useful to me, but I can only enable this on dark knight or black mage currently.

**Comment by jacob-keller** [comment]
The reason I want support could be fixed by #7 which makes the mptbcd function work for all jobs regardless.

**Comment by marconsou** [comment]
Which other job you need to track mp regen ticks during countdown and for what reason?

The plugin hides it self/doesn't work if you are not playing as BLM and this is by design, this is not a bug or something.
I did add DRK because people figured out a very niche usage for this job, and i didn't add for everything else because this could bring more annoyance than solution (most of the time) for users. Even so, most features are disabled by default because they are specific for BLM.

Let's say someone is playing as DRG (which doesn't even use MP) and this plugin showing up on the screen would not make sense at all (unless someone figured out a very specific usage which makes sense).

Another reason is the data required to make this plugin works (in this case, make the progress bar goes from 0% to 100% constantly) is all about MP/HP natural regens (including umbral ice mp regens in this case), so things like DoT/HoT/Job specific abilities that work each 3 seconds **will not work** (unless they are coincidentally sync'ed with opcode data described early). 

A lot of people confuse "server tick" as one and only unique thing for all players. Even multiple BLMs on the same party, need different mp tracking time.

So, i need to know what are you trying to do.

What could make more sense (and keep the configuration more flexible for users) is to add all jobs that use MP on the list and let players check/uncheck which ones they want to. 
But instead, i decided to wait for people figured out a niche usage of this plugin for other jobs and bring this kind of discussion.

**Comment by SableCentaur** [comment]
The MP regen tick is shared with the HP regen tick, which is useful for anyone who wants to be at a precise HP threshold, not just BLM/DRK. It would be great to have this functionality available for everyone.
