### ISSUE TITLE
mp tick bar always visable while location is unlocked

### ISSUE THREAD

**Issue by Natehhggh** [marconsou/mp-tick-bar#9]
Version 1.4.1.4

Mp tick bar for both on black mage, and other jobs is no longer disappearing after recent update if location is not locked

Unlocked
![image](https://user-images.githubusercontent.com/7540679/193439167-fbb11ea6-4d9c-4faf-94e4-b8916f60b551.png)

Locked
![image](https://user-images.githubusercontent.com/7540679/193439186-d7905f29-5ec2-4761-aedb-5392e7136052.png)

**Comment by marconsou** [comment]
When you uncheck the **[Locked]** for progress bar, it will keep showing regardless your configuration/job because this is a temporary option used by users to adjust the position on screen then you check the **[Locked]** to lock it and remove the background window.

The background window (**[Locked]** is unchecked) means you can localize/move/resize your bar during your first time using the plugin, as described on the plugin menu. 

Some users couldn't find the progress bar at first, so putting a background window make it easier to localize on the screen and they don't even need to switch to Black Mage for it.

This option is not designed to show to the other jobs. It's designed to make it easier to move/place you progress bar on the screen.

So, on the first screen you are playing as a non-supported Job, but you are freely editing the position/size of the window of the progress bar because the **[Locked]** is unchecked. This is the reason you can see the progress bar with background window.

The second screen you checked the **[Locked]** which means you already placed the progress bar on the position you want, now you gonna start using it, but you are playing as a no-supported Job and all those conditions under **[Functional]** will take place, making the progress bar invisible.

**Comment by Natehhggh** [comment]
Sounds good, I didn't know there was a change to the expected behavior with this update
